### ISSUE TITLE
Support read-only mode

### ISSUE THREAD

**Issue by broneill** [cojen/Tupl#21]

**Comment by tylaar** [comment]
for Supporting ReadOnly mode, is it necessary to create a new PagedDB subClass which provides the functionality of reading values from DB, but disable all the writing functions inside ? Or we reuse the DurablePageDb class and check the readOnly mode inside to perform the operations ?

**Comment by tylaar** [comment]
If we use the NoPagedBd class, then I think it's the same as allowing in-memory changes.

**Comment by broneill** [comment]
I think the mode should be "fileReadOnly(true)", and allow changes to made in-memory. The PageArray is opened in read-only mode, preventing writes. New checks are required for providing better exceptions.

**Comment by tylaar** [comment]
I've been modifying in my fork for readOnly in a lot fields, I found that multiple choices are available for supporting readOnly. For instance, RedoWriter, in my perspective,  since ReadOnly mode will not allow RedoLog/UndoLog creation, one possible way to do it is to create a DummyRedoWriter, which inside, write. checkpoint functions will just pass and do nothing. Another way is to throw ReadOnlyModeException during certain API call, like someone wants to call checkpoint on Database class. Are these two ways all acceptable ?

**Comment by tylaar** [comment]
Another question is for Snapshot function. If snapshot isn't allowed to create TempDatabase, then how can we do it ? Directly snapshot to memory only ?
