### ISSUE TITLE
ACID Properties?

### ISSUE THREAD

**Issue by MartinHaeusler** [cojen/Tupl#63]
Hi,

I just stumbled across this project by accident, and I think it's really interesting! I have a couple of questions though, so if you don't mind, I will put them right here:

1. How does this project compare to [MapDB](http://www.mapdb.org/)?
2. How ACID are your transactions? 
2.1. What is your maximum supported [Isolation Level](https://en.wikipedia.org/wiki/Isolation_(database_systems))?
2.2. Are writes atomic and durable, i.e. what happens if the JVM is shut down during a commit (power loss, process killed, ...)? Will this corrupt the store?
2.3. Are you using pessimistic locking, or is there some [MVCC](https://en.wikipedia.org/wiki/Multiversion_concurrency_control) algorithm in place?
3. How exactly do you define `greater/equal` for `byte[]`?
3.1. Is there a way to convert a `java.lang.String` into a `byte[]` such that the `greater/equal` order for the `byte[]` is equivalent to the `String.compareTo(...)` order?
4. What's the maximum size of the `byte[]`s for keys and values? Is there a maximum?
5. How fast is your store, i.e. how many queries / retrieved elements per second compared to MapDB?

Sorry for this flood of questions, I chose to use an issue rather than e-mail because this might be interesting for other people as well.

**Comment by broneill** [comment]
1. Tupl offers a lower-level API than MapDB, with the intent that it can be used for building higher-level systems. That is, a MapDB like API could be layered on top, or a relational DB, etc.
2. How ACID?
2.1. Isolation levels are selected with the [LockMode](https://cojen.github.io/Tupl/javadoc/org/cojen/tupl/LockMode.html) enum. Note the lack of serializable or snapshot isolation.
2.2. Neither JVM failure, OS crash, or power failures can corrupt the store. If a weak [DurabilityMode](https://cojen.github.io/Tupl/javadoc/org/cojen/tupl/DurabilityMode.html) is used, then recent transactions might rollback. Atomicity isn't compromised.
2.3. Only pessimistic locking. I've come up with some ideas for supporting read-only snapshots, but I'm not too keen on incorporating fully optimistic transactions. Some of its capabilities can be achieved by setting the transaction lock timeout to zero, however.
3. Byte arrays are lexicographically ordered, treating the bytes as unsigned.
3.1. Storing the string as UTF-8 will maintain equivalent comparison order. This is a nice property of UTF-8 encoding. Tupl doesn't contain any utilities for supporting more complex key encodings, nor does it support custom comparators. An earlier project I worked on, Carbonado, does support complex encodings and it also works with Tupl. Carbonado is a bit dated, however, and it doesn't perform as well as I would like anymore.
4. Keys and values can be as large as 2GiB. I don't recommend using super large keys, since they're not optimized. Keys less than about 2000 bytes are optimized. At some point I want to expand the maximum value size, by adding a "blob" API. The store itself internally allows values to be as large as 1EiB (with the default page size).
5. I've not compared Tupl to MapDB with respect to performance. A key design principle of Tupl is to minimize garbage collection churn, and so it allocates very few objects. It also tries to store data in memory allocated outside the Java heap (direct page access), and no data transformations are made when moving pages to and from persistent storage.

Also see the [FAQ](https://github.com/cojen/Tupl/wiki/FAQ)

**Comment by MartinHaeusler** [comment]
Hi,

first of all, thanks for getting back to me and answer my questions so fast, much appreciated :)

A few comments on your answers.

1. Perfectly clear. Might be just what I needed.
2.1. Very nice! Thumbs up for repeatable reads!
2.2. Perfect.
2.3. No big deal, really. It was more curiosity than actual need on my side.
3. I didn't know that UTF-8 had such a neat trick up its sleeve! That's all I need for my purposes.
4. That's way more than enough for what I intend to do :)
5. No big deal, I was just curious.

It seems like Tupl could be just the ideal replacement for MapDB I have been looking for, very interesting. I see a lot of details here that I like **a lot**. I will need to run some experiments on my own. In case it turns out that Tupl really manages to keep all the things you just promised (which is one hell of a challenge!) and in addition is comparably fast as MapDB, then I might end up using it :)

If you don't mind, I do have a couple of follow-up questions...

6. Does Tupl have the requirement that the entire store needs to fit into RAM? Or do you perform some sort of page loading/unloading in the background in cases where the database is larger than the available RAM?
7. Is the initial startup time of a Tupl instance depending on the size of the database, or is it independent? In other words, does Tupl startup take longer on a 10GB database than on a 100MB database?

**Comment by broneill** [comment]
Tupl doesn't require that the database fit in RAM. Pages are evicted as required, selecting the least recently used ones first. You should always choose a large cache size for best performance.

Tupl startup time is influenced by redo log recovery time and cache size. If a lot of changes were written to the redo log before a checkpoint was issued, then all those operations need to be replayed when the database is opened again. This cost can be reduced by enabling a [cache primer](https://cojen.github.io/Tupl/javadoc/org/cojen/tupl/DatabaseConfig.html#cachePriming-boolean-), which pre-fetches pages before replaying the redo log.  When you configure a very large cache (>10GiB), it can take a few seconds for the pages to be allocated by the operating system itself. If you install an EventListener/EventPrinter, you can see how long each step takes.

**Comment by MartinHaeusler** [comment]
Very good, thanks! I will give it a try soon!
